Update npm-check to ignore updates
pelias/placeholder pull request #10
Opened 2017-05-15 17:25 UTC by dianashk

:robot: *This pull request has been automatically generated by repo-crawler.* :robot:

2017-05-15 22:11 UTC, trescube approved these changes

2017-05-15 22:13 UTC, orangejulius requested changes
this doesn't install the `npm-check` module, does it?

2017-05-16 12:56 UTC, dianashk commented
Yeah not yet. I started working on a PR to add it but got bogged down in lint check failures. I'd like to add all the traditional timing for this repo. Will have the PR ready soon.

2017-05-16 13:37 UTC, dianashk commented
Closing this in favor of a new incoming PR with all the traditional tooling.

2017-05-16 13:37 UTC, closed without merging