analysis: better support for apostrophe s
pelias/placeholder pull request #20
Opened 2017-05-18 18:16 UTC by missinglink

better support for 'apostrophe s'.

I noticed that `St. George's, Grenada` was being tokenized as `[ 'st georges grenada', 'st george s grenada' ]`

this PR still tokenizes it in the singular and plural forms but drops the extra 's' token:

```
[ 'st georges grenada', 'st george grenada' ]
```

2017-05-18 19:19 UTC, trescube requested changes
See #21

2017-05-19 11:07 UTC, missinglink commented
commit for non-standard apostrophes.

fixes https://github.com/pelias/placeholder/issues/21

2017-05-19 14:22 UTC, dianashk approved these changes

2017-05-19 14:56 UTC, trescube approved these changes

2017-05-19 14:57 UTC, merged