added request logging with response times
pelias/placeholder pull request #59
Opened 2017-10-03 14:55 UTC by trescube

2017-10-03 14:57 UTC, orangejulius requested changes

2017-10-03 14:57 UTC, orangejulius commented on package.json
> +    "pelias-logger": "^0.2.0",
use an exact version :) NPM doesn't by default

2017-10-03 15:11 UTC, orangejulius approved these changes
Code looks good to me. Unfortunately the way the Travis tests are set up right now, they'll only ever pass on the same day we've pushed data. So either we merge anyway (the tests with the latest data passed on my machine), build new data, or figure out a new way to test.

2017-10-03 15:13 UTC, merged

2017-10-04 09:45 UTC, missinglink reviewed
This code looks fairly generic, could we include this middleware in the pelias/logger repo to avoid duplication?